# Generated by Django 4.0.1 on 2022-02-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('rest', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routine')),
            ],
        ),
        migrations.CreateModel(
            name='transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='transformation')),
            ],
        ),
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.set')),
            ],
        ),
        migrations.CreateModel(
            name='rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.CharField(max_length=120)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workout')),
            ],
        ),
        migrations.CreateModel(
            name='instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workout')),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workout')),
            ],
        ),
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.set')),
            ],
        ),
    ]
