# Generated by Django 4.0.1 on 2022-02-04 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='date',
            name='set',
        ),
        migrations.AddField(
            model_name='data',
            name='set',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, to='home.set'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.date'),
        ),
    ]
